name: 17 - 3 - Custom Actions - JS
run-name: 17 - 3 - Custom Actions - JS
on:
   workflow_dispatch:
    inputs:
      base-branch:
        description: 'The branch used as the base for the dependency update checks.'
        default: 'main'
        required: false
      target-branch:
        description: 'The branch from which the PR is created.'
        default: 'update-dependencies'
        required: false
      working-directory:
        description: 'The working directory of the project to check for dependency updates.'
        required: true
        default: 'react-app'
      debug:
        description: 'Whether the output debug messages to the console.'
        required: false
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
       - name: 'Checkout Code'          
         uses: actions/checkout@v4

       - name: Check for dependency updates
         uses: ./.github/actions/js-dependency-update
         with:
            base-branch: ${{ inputs.base-branch }}
            head-branch: ${{ inputs.target-branch }}
            working-directory: ${{ inputs.working-directory }}
            gh-token: ${{ secrets.GITHUB_TOKEN }}
            debug: ${{ inputs.debug }}
     
#secrets.GH_TOKEN
