name:  a - Managing Concurrency
on:
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    slow-greet:
        runs-on: ubuntu-latest
        steps:
            - name: Greet with a delay
              run: |
                    echo "Hello! This is a slow greeting."
                    sleep 30