name: 18 - 1 - Managing Concurrency

on:
  workflow_dispatch:

jobs:
  slow-greet:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Slow greeting
        run: |
          echo "Hola desde slow-greet..."
          sleep 30
          echo "slow-greet terminado!"

  slow-but-important-greet:
    runs-on: ubuntu-latest

    steps:
      - name: Important greeting
        run: |
          echo "Hola desde slow-but-important-greet..."
          sleep 30
          echo "slow-but-important-greet terminado!"